import streamlit as st
import plotly.express as px
from ai_handler import AIHandler
import main
from ui_components import render_swot_card
# 1. KONFIGURASI HALAMAN
st.set_page_config(
    page_title="Pathfinder.ai", 
    page_icon="👩🏻‍🎓", 
    layout="wide"
)

# 2. SISTEM DWIBAHASA (Dictionary)
lang_dict = {
    "BM": {
        "warning_input": "⚠️ Sila masukkan minat, subjek, atau cita-cita untuk dianalisis",
        "search_title": "👩🏻‍🎓Pathfinder.ai",
        "input_label": "Minat / Bidang Kajian:",
        "input_placeholder": "Contoh: Saya minat Matematik dan pengekodan komputer...",
        "btn_analyze": "jana",
        "disclaimer_title": "PENAFIAN:",
        "disclaimer_text": "Analisis ini dijana secara automatik oleh AI untuk tujuan rujukan dan panduan akademik sahaja.",
        "main_title": "👩🏻‍🎓 Panduan Hala Tuju Akademik & Kerjaya",
        "main_subtitle": "Sistem Analisis Strategik Masa Depan Berkuasa AI Llama 3.3",
        "card_career": "💼 PROSPEK KERJAYA",
        "card_university": "🎓 CADANGAN KURSUS UNIVERSITI",
        "card_field": "📈 SKOR KESESUAIAN BIDANG",
        "card_trend": "🔥 STATUS TREND KERJAYA",
        "chart_title": "📊 Projeksi Keperluan Industri Masa Depan (Simulasi 5 Tahun)",
        "swot_title": "🎯 Analisis SWOT Pelajar & Kerjaya",
        "recommended_field_title": "💡 Saranan Pintar: Bidang Masa Depan Alternatif",
        "recommended_field_reason": "Kenapa AI Mencadangkan Ini:",
        "recommended_field_jobs": "Contoh Kerjaya Baharu:",
        "footer": "Pembangun: Ameerah Safiah | Bakal Mahasiswa Kejuruteraan Perisian UKM",
        "loading": "🤖 AI sedang merangka hala tuju masa depan anda...",
        "info_msg": "Sila pilih bahasa di menu tepi dan masukkan minat atau bidang akademik anda untuk menjana analisis hala tuju penuh."
    },
    "EN": {
        "warning_input": "⚠️ Please enter your interests, subjects, or career goals to analyze",
        "search_title": "👩🏻‍🎓Pathfinder.ai",
        "input_label": "Interests / Field of Study:",
        "input_placeholder": "Example: I love Biology and helping people...",
        "btn_analyze": "Generate",
        "disclaimer_title": "DISCLAIMER:",
        "disclaimer_text": "This analysis is automatically generated by AI for educational reference and guidance only.",
        "main_title": "👩🏻‍🎓 Academic & Career Path Guidance",
        "main_subtitle": "Future Strategic Analysis System Powered by AI Llama 3.3",
        "card_career": "💼 CAREER PROSPECTS",
        "card_university": "🎓 RECOMMENDED UNIVERSITY COURSES",
        "card_field": "📈 FIELD SUITABILITY SCORE",
        "card_trend": "🔥 CURRENT JOB TREND STATUS",
        "chart_title": "📊 Industry Demand Projection (5-Year Simulation)",
        "swot_title": "🎯 Student & Career SWOT Analysis",
        "recommended_field_title": "💡 Smart Recommendation: Alternative Future Fields",
        "recommended_field_reason": "Why AI Recommends This:",
        "recommended_field_jobs": "Emerging Career Examples:",
        "footer": "Developer: Ameerah Safiah | UKM Software Engineering Applicant",
        "loading": "🤖 AI is formulating your future path data...",
        "info_msg": "Please select a language from the sidebar and enter your academic interests to generate a full path analysis."
    }
}

# 3. CSS STYLE 
st.markdown("""
    <style>
    .stApp { background-color: #f8fafc; color: #1e293b; }
    [data-testid="stSidebar"] { background-color: #ffffff; border-right: 1px solid #e2e8f0; }
    
    /* Grid Metrik */
    .card {
        background-color: #ffffff; padding: 24px; border-radius: 12px;
        border: 1px solid #e2e8f0; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
        text-align: left; color: #1e293b; height: 100%;
    }
    .card-title { color: #64748b; font-size: 0.85rem; font-weight: bold; margin-bottom: 8px; text-transform: uppercase; }
    .card-value { color: #2563eb; font-size: 1.2rem; font-weight: 600; line-height: 1.5; }
    .university-text { color: #059669; font-size: 1.1rem; font-weight: bold; line-height: 1.5; }
    
    /* Kotak Ungu Sampingan */
    .rec-box {
        background-color: #f5f3ff; padding: 24px; border-radius: 12px;
        border: 1px solid #ddd6fe; box-shadow: 0 4px 6px -1px rgba(124, 58, 237, 0.05);
        margin: 15px 0;
    }
    .rec-title { color: #6d28d9; font-size: 1.2rem; font-weight: bold; margin-bottom: 5px; }
    .rec-subtitle { color: #4c1d95; font-size: 0.95rem; font-weight: 600; margin-top: 12px; margin-bottom: 4px; }
    
    .disclaimer-box { font-size: 0.8rem; color: #64748b; background-color: #f1f5f9; padding: 15px; border-radius: 8px; border-left: 4px solid #94a3b8; margin-top: 20px; }
    
    /* Butang Sebelah Input */
    .stButton > button {
        background-color: #549acf; 
        color: #ffffff ; 
        border: none ; 
        padding: 10px 14px ; 
        border-radius: 10px ;
        box-shadow: 0 2px 4px rgba(84, 154, 207, 0.15) ;
    }
    .stButton > button:hover { background-color: #3f7fc0 ; }
    </style>
    """, unsafe_allow_html=True)

handler = AIHandler()

# 4. SIDEBAR & PEMILIHAN BAHASA
with st.sidebar:
    st.image("https://png.pngtree.com/png-vector/20190508/ourmid/pngtree-navigation-vector-icon-png-image_1027011.jpg", width=70)
    
    sel_lang = st.selectbox("🌐 Language / Bahasa", ["English", "Bahasa Melayu"])
    if sel_lang == "Bahasa Melayu":
        L = lang_dict["BM"]
    else:
        L = lang_dict["EN"]
    st.markdown("---")
    st.markdown(f'''
        <div class="disclaimer-box">
            <b>{L["disclaimer_title"]}</b><br>
            {L["disclaimer_text"]}
        </div>
    ''', unsafe_allow_html=True)

# 5. KANDUNGAN UTAMA (Input & Button Bersebelahan)
st.title(L["main_title"])
st.write(f"{L['main_subtitle']} • First Edition")
st.markdown("---")

col1, col2 = st.columns([4, 1])

with col1:
    topic = st.text_input(
        L["input_label"], 
        placeholder=L["input_placeholder"], 
        label_visibility="collapsed"
    )

with col2:
    generate_btn = st.button(L["btn_analyze"], use_container_width=True)

# 6. LOGIK PEMPROSESAN OUTPUT AI
if generate_btn:
    if topic:
        with st.spinner(L["loading"]):
            if sel_lang == "English":
                ai_lang_instruction = "Professional English"
            else:
                ai_lang_instruction = "Bahasa Melayu Korporat"
        
        #ini 1
        #ini1

            # Panggil AI Handler
            res = handler.analyze_market(topic, lang=ai_lang_instruction)
            
            if "error" in res:
                st.error(res["error"])
            else:
                # BARIS 1: GRID METRIK ULU
                row1_col1, row1_col2 = st.columns(2)
                with row1_col1:
                    st.markdown(f'<div class="card"><div class="card-title">{L["card_career"]}</div><div class="card-value" style="font-size: 1rem; font-weight: normal; color: #1e293b;">{res.get("prospek_kerjaya", "N/A")}</div></div>', unsafe_allow_html=True)
                with row1_col2:
                    st.markdown(f'<div class="card"><div class="card-title">{L["card_university"]}</div><div class="university-text">{res.get("cadangan_kursus_universiti", "N/A")}</div></div>', unsafe_allow_html=True)

                st.write("") 

                row2_col1, row2_col2 = st.columns(2)
                with row2_col1:
                    st.markdown(f'<div class="card"><div class="card-title">{L["card_field"]}</div><div class="card-value">{res.get("skor_kesesuaian", 0)}%</div></div>', unsafe_allow_html=True)
                with row2_col2:
                    st.markdown(f'<div class="card"><div class="card-title">{L["card_trend"]}</div><div class="card-value">{res.get("status_trend_kerjaya", "N/A")}</div></div>', unsafe_allow_html=True)

                # BARIS 2: SWOT ANALYSIS
                st.markdown("---")
                st.subheader(L["swot_title"])
                swot = res.get("swot_pelajar", {})
                s1, s2, s3, s4 = st.columns(4)
                
                if sel_lang == "English":
                    labels = ["Strengths", "Weaknesses", "Opportunities", "Threats"]
                else:
                    labels = ["Kekuatan", "Kelemahan", "Peluang", "Ancaman"]
                with s1:
                    render_swot_card("💪", f"{labels[0]}", swot.get("kekuatan", []), "#7C3AED", "linear-gradient(145deg, #F5F3FF, #EDEDFF)")

                with s2:
                    render_swot_card("⚠️", f"{labels[1]}", swot.get("kelemahan", []), "#EC4899", "linear-gradient(145deg, #FDF2F8, #FCE7F3)")
                                
                #with s2:
                    #st.error(f"⚠️ **{labels[1]}**")
                    #for p in swot.get("kelemahan", []): st.write(f"• {p}")
                with s3:
                    render_swot_card("🚀", f"{labels[2]}", swot.get("peluang", []), "#10B981", "linear-gradient(145deg, #F0FDF4, #DCFCE7)")

                with s4:
                    render_swot_card("🛡️", f"{labels[3]}", swot.get("ancaman", []), "#F59E0B", "linear-gradient(145deg, #FFFbeb, #FEF3C7)")

                # BARIS 3: KOTAK BIDANG ALTERNATIF (PINTAR)
                st.markdown("---")
                st.subheader(L["recommended_field_title"])
                rec_field = res.get("bidang_sampingan_disyorkan", {})
                
                if rec_field:
                    st.markdown(f'''
                        <div class="rec-box">
                            <div class="rec-title">✨ {rec_field.get('nama_bidang', 'Bidang Teknologi Masa Depan')}</div>
                            <hr style="border: 0; border-top: 1px solid #ddd6fe; margin: 10px 0;">
                            <div class="rec-subtitle">💡 {L['recommended_field_reason']}</div>
                            <p style="font-size: 0.95rem; line-height: 1.6; color: #1e293b;">{rec_field.get('sebab_disyorkan', '')}</p>
                        </div>
                    ''', unsafe_allow_html=True)
                    
                    st.markdown(f"**{L['recommended_field_jobs']}**")
                    job_cols = st.columns(len(rec_field.get("contoh_kerjaya", [1, 2])))
                    for i, job in enumerate(rec_field.get("contoh_kerjaya", [])):
                        with job_cols[i]:
                            st.info(f"🔹 {job}")

                # BARIS 4: GRAF (PROJEKSI)
                st.markdown("---")
                st.subheader(L["chart_title"])
                df_plot = main.generate_visual_data()
                fig = px.area(df_plot, x='tahun', y='Minat Pasaran', template="plotly_white", height=350) 
                fig.update_traces(line_color='#2563eb', fillcolor='rgba(37, 99, 235, 0.1)')
                fig.update_layout(
                    yaxis_title="Keperluan Industri (%)" if sel_lang == "Bahasa Melayu" else "Industry Demand (%)", 
                    xaxis_title="Garis Masa (Tahun)" if sel_lang == "Bahasa Melayu" else "Timeline (Years)"
                )
                st.plotly_chart(fig, use_container_width=True)

                # FOOTER & ADVICE
                st.markdown("---")
                st.info(f"💡 {res.get('nasihat_akademik', 'Teruskan berusaha membina kemahiran diri.')}")
                st.caption(L["footer"])
    else:
        st.warning(L["warning_input"])
else:
    # Paparan Muka Hadapan (Landing Page)
    st.markdown("<br><br>", unsafe_allow_html=True)
    c1, c2, c3 = st.columns([1, 2, 1])
    with c2:
        st.image("https://img.freepik.com/free-vector/data-analysis-concept-illustration_114360-8013.jpg", use_container_width=True)
        st.info(L["info_msg"])